version: "3.0"

services: 
  user:
    build: UserService
    image: user_service
    ports: 
      - "3001:3001"
  plan:
    build: PlanService
    image: plan_service
    ports: 
      - "3002:3002"
  group:
    build: GroupService
    image: group_service
    ports: 
      - "3003:3003"
  friend:
    build: FriendService
    image: friend_service
    ports: 
      - "3004:3004"
  file:
    build: FileService
    image: file_service
    volumes:
      - ./FileService/uploads:/app/uploads
    ports: 
      - "3005:3005"