workflows:
  version: 2
  build-deploy:
    jobs:
    - build:
        filters:
          branches:
            only: master
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
version: 2.0
jobs:
  build:
    machine: 
      services:
        - docker
    working_directory: ~/Plan2Task-BackEnd
    steps:
      - checkout
      - run: docker-compose down
      - run: docker image prune -f
      - run: docker-compose up --build -d
  deploy:
    machine: true
    working_directory: ~/Plan2Task-BackEnd
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $fingerprint
      - run:
          name: Deploy Plan2Task
          command: |
            ssh $SSH_USER@$SSH_HOST  \
            '
              cd /var/Plan2Task-BackEnd &&
              sudo docker-compose down &&
              sudo docker image prune -f &&
              sudo git pull &&
              sudo docker-compose up --build -d
            '
